name: Accessibility Tests with Axe
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm ci
          npm run build --if-present
          npm install -g @axe-core/cli@4.x.x

      - name: Start Axe server
        run: npm start & npx wait-on https://localhost:8080

      - name: Run axe
        run: |
          axe https://localhost:8080 --reporter html > axe-report.html --exit
