name: Accessibility Tests with Axe
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g @axe-core/cli@4.x.x

      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe https://emma11y.github.io/tester-a11y/ --exit
