name: axe
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on https://emma11y.github.io/tester-a11y/
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe https://emma11y.github.io/tester-a11y/ --exit
