name: Accessibility Tests with Pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g @pa11y@8.0.0

      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y http://localhost:8080
