name: Accessibility Tests with Pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm ci
          npm run build --if-present
          npm install -g pa11y@8.0.0

      - name: Start Axe server
        run: npm start & npx wait-on https://localhost:8080

      - name: Run pa11y
        run: |
          pa11y https://localhost:8080 --reporter html > pa11y-report.html
