name: Accessibility Tests with Pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm ci
          npm run build --if-present
          npm run dev & npx wait-on http://localhost:5173/

      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y http://localhost:5173/tester-a11y/
          pa11y http://localhost:5173/tester-a11y/cas-pratique-1 
          pa11y http://localhost:5173/tester-a11y/cas-pratique-2 
          pa11y http://localhost:5173/tester-a11y/cas-pratique-3
          pa11y http://localhost:5173/tester-a11y/cas-pratique-4 
          pa11y http://localhost:5173/tester-a11y/cas-pratique-5 
          pa11y http://localhost:5173/tester-a11y/cas-pratique-6
